### ISSUE TITLE
Plugin "Microsoft Teams Notifications" crashing on TC9

### ISSUE THREAD

**Issue by CeddaerrixGE** [spyder007/teamcity-msteams-notifier#27]
After discovering its existence in a post, I have downloded the plugin presented under https://plugins.jetbrains.com/plugin/12645-microsoft-teams-notifications

When trying to use the 'Add project MsTeams notifications', I received an unexpected error with the following content

> Unexpected Error
> This was not supposed to happen. Please provide the error details to your TeamCity server maintainer.
> If you maintain this TeamCity installation please report this error to JetBrains.
> 
> Error message: jetbrains.buildServer.serverSide.SBuildServer.getVersion()Ljetbrains/buildServer/version/ServerVersionInfo;
> TeamCity: 9.1.7 (build 37573)
> Operating system: Windows Server 2008 R2 (6.1, x86)
> Java: 1.8.0_66-b17 (Oracle Corporation)
> Servlet container: Apache Tomcat/7.0.59
> 
> Trace: java.lang.NoSuchMethodError: jetbrains.buildServer.serverSide.SBuildServer.getVersion()Ljetbrains/buildServer/version/ServerVersionInfo;
> 	at msteamsnotifications.teamcity.extension.MsTeamsNotificationIndexPageController.doHandle(MsTeamsNotificationIndexPageController.java:68)
> 	at jetbrains.buildServer.controllers.BaseController.handleRequestInternal(BaseController.java:75)
> 	at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:154)
> 	at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:50)
> 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:938)
> 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:870)
> 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:961)
> 	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:852)
> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:620)
> 	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:837)
> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
> 	at jetbrains.buildServer.maintenance.TeamCityDispatcherServlet.service(TeamCityDispatcherServlet.java:38)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
> 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
> 	at jetbrains.buildServer.web.DependencyParametersCalculationContextFilter.doFilter(DependencyParametersCalculationContextFilter.java:9)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
> 	at jetbrains.buildServer.web.DisableSessionIdFromUrlFilter.doFilter(DisableSessionIdFromUrlFilter.java:1)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
> 	at jetbrains.buildServer.diagnostic.web.DiagnosticFilter.doFilter(DiagnosticFilter.java:46)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
> 	at jetbrains.buildServer.web.ResponseFragmentFilter.doFilter(ResponseFragmentFilter.java:6)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
> 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
> 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
> 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
> 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
> 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
> 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:421)
> 	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1074)
> 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611)
> 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1739)
> 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1698)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
> 	at java.lang.Thread.run(Thread.java:745)

**Comment by wacannon** [comment]
Getting the same error.  Is this going to be fixed or an older version we can use that works with TC9.

**Comment by spyder007** [comment]
The earliest version supported was TC 10.  I upgraded this package last June to the latest.

Best I could advise is trying 1.0.7, that may be compatible with TC 9.
https://github.com/spyder007/teamcity-msteams-notifier/releases/tag/1.0.7

**Comment by wacannon** [comment]
I rolled back to release 2.0.0 and that seems to be working with TC ver. 9.1.1

**Comment by spyder007** [comment]
@wacannon I'm surprised that worked, that version should be the first version with the updated references.  I don't believe i've updated TC references since then.
